import type { PropertyData, ReviewData, DashboardStats } from '../types/dashboard';

export const mockProperties: PropertyData[] = [
 {
  id: 'prop-1',
  name: '2B N1 A - 29 Shoreditch Heights',
  location: 'Shoreditch, London',
  city: 'London',
  type: 'Apartment',
  bedrooms: 2,
  bathrooms: 2,
  rating: 4.8,
  totalReviews: 24,
  occupancyRate: 92,
  revenue: 15420,
  revenueChange: 12.5,
  lastUpdated: '2024-01-15',
  status: 'Active',
  image: '/modern-london-apartment-exterior.jpg',
  totalBookings: 45,
  bookingsChange: 8.2,
  cancellations: 3,
  cancellationRate: 6.7,
  averageStayLength: 4.2,
  cleaningFees: 1200,
  maintenanceCosts: 850,
  netProfit: 13370,
  profitMargin: 86.7,
  lastBooking: '2024-01-12',
  nextBooking: '2024-01-18',
  categoryRatings: {
   cleanliness: 9.0,
   communication: 8.5,
   location: 9.2,
   checkin: 8.8,
   accuracy: 8.7,
   value: 8.3
  }
 },
 {
  id: 'prop-2',
  name: '1B E1 B - 15 Canary Wharf Tower',
  location: 'Canary Wharf, London',
  city: 'London',
  type: 'Apartment',
  bedrooms: 1,
  bathrooms: 1,
  rating: 4.9,
  totalReviews: 18,
  occupancyRate: 88,
  revenue: 12850,
  revenueChange: 8.3,
  lastUpdated: '2024-01-14',
  status: 'Active',
  image: '/luxury-canary-wharf-apartment.jpg',
  totalBookings: 38,
  bookingsChange: 12.1,
  cancellations: 2,
  cancellationRate: 5.3,
  averageStayLength: 3.8,
  cleaningFees: 950,
  maintenanceCosts: 650,
  netProfit: 11250,
  profitMargin: 87.5,
  lastBooking: '2024-01-10',
  nextBooking: '2024-01-16',
  categoryRatings: {
   cleanliness: 9.2,
   communication: 9.0,
   location: 9.5,
   checkin: 9.1,
   accuracy: 8.9,
   value: 8.8
  }
 },
 {
  id: 'prop-3',
  name: 'Studio W1 C - 42 Fitzrovia Square',
  location: 'Fitzrovia, London',
  city: 'London',
  type: 'Studio',
  bedrooms: 0,
  bathrooms: 1,
  rating: 4.7,
  totalReviews: 31,
  occupancyRate: 85,
  revenue: 9650,
  revenueChange: -2.1,
  lastUpdated: '2024-01-13',
  status: 'Active',
  image: '/stylish-fitzrovia-studio-apartment.jpg',
  totalBookings: 52,
  bookingsChange: -5.2,
  cancellations: 7,
  cancellationRate: 13.5,
  averageStayLength: 2.8,
  cleaningFees: 780,
  maintenanceCosts: 420,
  netProfit: 8450,
  profitMargin: 87.6,
  lastBooking: '2024-01-08',
  nextBooking: '2024-01-20',
  categoryRatings: {
   cleanliness: 8.8,
   communication: 8.2,
   location: 9.0,
   checkin: 8.5,
   accuracy: 8.3,
   value: 8.0
  }
 },
 {
  id: 'prop-4',
  name: '3B Champs-Élysées - 15 Avenue',
  location: 'Champs-Élysées, Paris',
  city: 'Paris',
  type: 'Apartment',
  bedrooms: 3,
  bathrooms: 2,
  rating: 4.6,
  totalReviews: 12,
  occupancyRate: 78,
  revenue: 18750,
  revenueChange: 15.2,
  lastUpdated: '2024-01-12',
  status: 'Active',
  image: '/modern-furnished-apartment-living-room.jpg',
  totalBookings: 28,
  bookingsChange: 18.5,
  cancellations: 1,
  cancellationRate: 3.6,
  averageStayLength: 6.1,
  cleaningFees: 1500,
  maintenanceCosts: 1200,
  netProfit: 16050,
  profitMargin: 85.6,
  lastBooking: '2024-01-09',
  nextBooking: '2024-01-22',
  categoryRatings: {
   cleanliness: 9.1,
   communication: 8.7,
   location: 9.4,
   checkin: 8.9,
   accuracy: 8.6,
   value: 8.4
  }
 },
 {
  id: 'prop-5',
  name: '2B Algiers Center - 8 Rue Didouche',
  location: 'Algiers Center, Algiers',
  city: 'Algiers',
  type: 'Apartment',
  bedrooms: 2,
  bathrooms: 1,
  rating: 4.4,
  totalReviews: 8,
  occupancyRate: 65,
  revenue: 4200,
  revenueChange: 22.8,
  lastUpdated: '2024-01-11',
  status: 'Active',
  image: '/modern-apartment-bedroom-with-natural-light.jpg',
  totalBookings: 18,
  bookingsChange: 25.0,
  cancellations: 2,
  cancellationRate: 11.1,
  averageStayLength: 3.2,
  cleaningFees: 320,
  maintenanceCosts: 180,
  netProfit: 3700,
  profitMargin: 88.1,
  lastBooking: '2024-01-05',
  nextBooking: '2024-01-25',
  categoryRatings: {
   cleanliness: 8.5,
   communication: 8.0,
   location: 8.8,
   checkin: 8.3,
   accuracy: 8.1,
   value: 8.6
  }
 },
 {
  id: 'prop-6',
  name: '1B Marais - 22 Rue des Archives',
  location: 'Le Marais, Paris',
  city: 'Paris',
  type: 'Apartment',
  bedrooms: 1,
  bathrooms: 1,
  rating: 4.5,
  totalReviews: 15,
  occupancyRate: 82,
  revenue: 11200,
  revenueChange: 5.7,
  lastUpdated: '2024-01-10',
  status: 'Maintenance',
  image: '/stylish-bedroom-with-yellow-accents-and-artwork.jpg',
  totalBookings: 35,
  bookingsChange: 3.2,
  cancellations: 4,
  cancellationRate: 11.4,
  averageStayLength: 4.5,
  cleaningFees: 890,
  maintenanceCosts: 750,
  netProfit: 9560,
  profitMargin: 85.4,
  lastBooking: '2024-01-07',
  nextBooking: '2024-01-28',
  categoryRatings: {
   cleanliness: 8.9,
   communication: 8.4,
   location: 9.1,
   checkin: 8.6,
   accuracy: 8.5,
   value: 8.2
  }
 }
];

export const mockReviews: ReviewData[] = [
 {
  id: 'rev-1',
  propertyId: 'prop-1',
  propertyName: '2B N1 A - 29 Shoreditch Heights',
  guestName: 'Sarah Johnson',
  rating: 5,
  comment: 'Absolutely perfect stay! The apartment was spotless and the location was ideal for exploring London.',
  channel: 'The Flex',
  category: 'Cleanliness',
  submittedAt: '2024-01-15T10:30:00Z',
  isApproved: true,
  isPublic: true
 },
 {
  id: 'rev-2',
  propertyId: 'prop-1',
  propertyName: '2B N1 A - 29 Shoreditch Heights',
  guestName: 'Michael Chen',
  rating: 4,
  comment: 'Great location and well-equipped apartment. Only minor issue was the WiFi speed.',
  channel: 'The Flex',
  category: 'Location',
  submittedAt: '2024-01-14T15:45:00Z',
  isApproved: true,
  isPublic: true
 },
 {
  id: 'rev-3',
  propertyId: 'prop-2',
  propertyName: '1B E1 B - 15 Canary Wharf Tower',
  guestName: 'Emma Wilson',
  rating: 5,
  comment: 'Luxury apartment with amazing views. Everything was perfect!',
  channel: 'The Flex',
  category: 'Value',
  submittedAt: '2024-01-13T09:20:00Z',
  isApproved: true,
  isPublic: true
 },
 {
  id: 'rev-4',
  propertyId: 'prop-3',
  propertyName: 'Studio W1 C - 42 Fitzrovia Square',
  guestName: 'David Brown',
  rating: 3,
  comment: 'The studio was smaller than expected and quite noisy at night.',
  channel: 'The Flex',
  category: 'Communication',
  submittedAt: '2024-01-12T14:15:00Z',
  isApproved: false,
  isPublic: false,
  managerNotes: 'Need to address noise issues and update listing description'
 },
 {
  id: 'rev-5',
  propertyId: 'prop-4',
  propertyName: '3B Champs-Élysées - 15 Avenue',
  guestName: 'Sophie Martin',
  rating: 4,
  comment: 'Beautiful apartment in perfect location. Check-in process was smooth.',
  channel: 'The Flex',
  category: 'Check-in',
  submittedAt: '2024-01-11T11:30:00Z',
  isApproved: true,
  isPublic: true
 },
 {
  id: 'rev-6',
  propertyId: 'prop-5',
  propertyName: '2B Algiers Center - 8 Rue Didouche',
  guestName: 'Ahmed Benali',
  rating: 4,
  comment: 'Good value for money. Clean and comfortable apartment.',
  channel: 'The Flex',
  category: 'Value',
  submittedAt: '2024-01-10T16:45:00Z',
  isApproved: true,
  isPublic: true
 }
];

export const mockDashboardStats: DashboardStats = {
 totalRevenue: 72370,
 revenueChange: 8.7,
 totalProperties: 6,
 propertiesChange: 0,
 totalReviews: 108,
 reviewsChange: 15.2,
 averageRating: 4.6,
 ratingChange: 0.3,
 occupancyRate: 82,
 occupancyChange: 5.2,
 responseRate: 94,
 responseChange: 2.1,
 pendingReviews: 3,
 approvedReviews: 95,
 rejectedReviews: 10
};
